### ISSUE TITLE
Foreign Key constraint failed creating a new watch zone

### ISSUE THREAD

**Issue by taekwonjoe01** [taekwonjoe01/sweepersd#110]
11-16 18:13:47.515 10585-11701/com.example.joseph.sweepersd E/AndroidRuntime: FATAL EXCEPTION: WatchZoneUpdater_1
                                                                              Process: com.example.joseph.sweepersd, PID: 10585
                                                                              android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
                                                                                  at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                                  at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                                                  at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                                  at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                                  at android.arch.persistence.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:79)
                                                                                  at android.arch.persistence.room.EntityInsertionAdapter.insertAndReturnIdsArray(EntityInsertionAdapter.java:133)
                                                                                  at com.example.joseph.sweepersd.watchzone.model.WatchZoneDao_Impl.insertWatchZonePointLimits(WatchZoneDao_Impl.java:209)
                                                                                  at com.example.joseph.sweepersd.watchzone.model.WatchZoneModelRepository.updateWatchZonePoint(WatchZoneModelRepository.java:104)
                                                                                  at com.example.joseph.sweepersd.watchzone.model.WatchZoneModelUpdater.saveWatchZonePoint(WatchZoneModelUpdater.java:359)
                                                                                  at com.example.joseph.sweepersd.watchzone.model.WatchZonePointUpdater.run(WatchZonePointUpdater.java:46)
                                                                                  at com.example.joseph.sweepersd.watchzone.model.WatchZoneUpdater$1.run(WatchZoneUpdater.java:96)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by taekwonjoe01** [comment]
Occurs 100% when "moving/deleting" a WZ that is being updated.
